package cli

import "fmt"

var managedRepositoryCreateFlags = flagNames("catalog repo command-id name store server as request-id trace-id span-id parent-span-id help")

func validateManagedRepositoryCreateFlags(flags map[string]FlagValue) error {
	if err := rejectFlagsOutside(flags, managedRepositoryCreateFlags, "kc catalog repo create"); err != nil {
		return err
	}
	return validateManagedRepositoryCoordinates(flags)
}

func validateManagedRepositoryCoordinates(flags map[string]FlagValue) error {
	if FlagString(flags, "name") != "" {
		if FlagString(flags, "repo") != "" || FlagString(flags, "command-id") != "" {
			return fmt.Errorf("--name cannot be combined with --repo or --command-id; managed coordinates are generated by Server")
		}
		return nil
	}
	for _, name := range []string{"catalog", "repo", "command-id"} {
		if _, err := requireRemoteFlag(flags, name); err != nil {
			return err
		}
	}
	return nil
}
