apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    uid: kc-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Jaeger
    uid: kc-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: kc-loki
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: -2m
        spanEndTimeShift: 2m

  - name: Loki
    uid: kc-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id[=:]"?([a-f0-9]{32})'
          datasourceUid: kc-jaeger
          url: '$${__value.raw}'
