package httpsurface

import "sort"

// Patterns is the closed public HTTP surface. CLI argv tables must not import
// this package; typed handlers register these patterns explicitly.
func Patterns() []string {
	out := append([]string{}, registry...)
	sort.Strings(out)
	return out
}

var registry = []string{
	"GET /repositories/{repository}",
	"GET /assets/repository.js",
	"GET /console",
	"GET /assets/console.js",
	"GET /ui/",
	"GET /admin/v1/grants",
	"GET /catalog/v1/catalogs",
	"GET /catalog/v1/repositories",
	"GET /catalog/v1/repositories/{repository}",
	"POST /catalog/v1/catalogs/{catalog}/repositories:connect",
	"GET /catalog/v1/repositories/{repository}/connection",
	"POST /catalog/v1/repositories/{repository}/connection:check",
	"POST /catalog/v1/repositories/{repository}/connection:rotate",
	"POST /catalog/v1/repositories",
	"GET /catalog/v1/catalogs/{catalog}",
	"GET /catalog/v1/catalogs/{catalog}/audit",
	"GET /catalog/v1/catalogs/{catalog}/repositories",
	"GET /catalog/v1/catalogs/{catalog}/datasets",
	"GET /catalog/v1/catalogs/{catalog}/datasets/{dataset}",
	"GET /health",
	"GET /identity/v1/auth",
	"GET /identity/v1/admission",
	"GET /catalog/v1/repositories/{repository}/shares",
	"POST /catalog/v1/repositories/{repository}/shares",
	"DELETE /catalog/v1/repositories/{repository}/shares/{share}",
	"GET /identity/v1/whoami",
	"POST /identity/v1/token",
	"POST /identity/v1/authorize",
	"POST /identity/v1/authorize:poll",
	"GET /livez",
	"GET /metrics",
	"GET /operations/v1/gates",
	"GET /operations/v1/hooks",
	"GET /operations/v1/stores",
	"GET /readyz",
	"GET /readyz/{surface}",
	"GET /writer/v1/receipts/{command}",
	"GET /writer/v1/repositories/{repository}/head",
	"POST /admin/v1/grants",
	"DELETE /admin/v1/grants/{grant}",
	"POST /catalog/v1/catalogs/{catalog}/archive",
	"POST /catalog/v1/catalogs/{catalog}/repositories",
	"POST /catalog/v1/catalogs/{catalog}/repositories:create",
	"POST /catalog/v1/catalogs/{catalog}/repositories/{repository}/archive",
	"DELETE /catalog/v1/catalogs/{catalog}/repositories/{repository}",
	"POST /catalog/v1/catalogs/{catalog}/datasets",
	"POST /catalog/v1/catalogs/{catalog}/datasets:resolve",
	"POST /catalog/v1/catalogs/{catalog}/datasets/{dataset}/check",
	"POST /catalog/v1/catalogs/{catalog}/datasets/{dataset}/resolve",
	"POST /catalog/v1/catalogs/{catalog}/datasets/{dataset}/retire",
	"POST /governance/v1/previews",
	"POST /governance/v1/previews:validate",
	"POST /governance/v1/proposals",
	"POST /governance/v1/proposals:merge",
	"POST /governance/v1/validations",
	"POST /knowledge/v1/bindings:resolve",
	"POST /knowledge/v1/log:query",
	"POST /knowledge/v1/objects:read",
	"POST /knowledge/v1/objects:resolve",
	"POST /knowledge/v1/provenance:describe",
	"POST /knowledge/v1/relations:query",
	"POST /knowledge/v1/rerank",
	"POST /knowledge/v1/resources:access",
	"POST /knowledge/v1/schemas:describe",
	"POST /knowledge/v1/schemas:list",
	"POST /knowledge/v1/search",
	"POST /knowledge/v1/search:rerank",
	"POST /operations/v1/access-log:query",
	"POST /operations/v1/access-specs:describe",
	"POST /operations/v1/feedback",
	"POST /operations/v1/gates",
	"DELETE /operations/v1/gates/{gate}",
	"POST /operations/v1/hitmap:query",
	"POST /operations/v1/hooks",
	"DELETE /operations/v1/hooks/{hook}",
	"POST /operations/v1/projections:describe",
	"POST /operations/v1/projections:notice",
	"POST /operations/v1/projections:sync",
	"POST /operations/v1/refine-log:query",
	"POST /operations/v1/rerank-training:query",
	"POST /operations/v1/retrieval-log:query",
	"POST /operations/v1/retrieval-training:query",
	"POST /operations/v1/traces:query",
	"POST /dataset-files/v1/file:read",
	"POST /dataset-files/v1/mounts:list",
	"POST /dataset-files/v1/tree:list",
	"POST /writer/v1/repositories/{repository}/commits",
}
