#!/usr/bin/env bash
# Select the Snapshot data plane. Local MinIO and online COS are isolated
# homes; KC still talks only to lakeFS. COS keys stay in the operator env.
# Usage: scripts/kc-snapshot-plane.sh local|online|status|down [local|online]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
export PATH="${HOME}/.local/go/bin:${PATH}"

CMD="${1:-status}"
TARGET="${2:-}"
GO="${GO:-go}"
CONFIG_DIR="${KC_PLANE_CONFIG_DIR:-${HOME}/.config/kc}"
ACTIVE_PLANE_FILE="${CONFIG_DIR}/active-plane"
ACTIVE_ENV_FILE="${CONFIG_DIR}/active.env"
COS_CONFIG="${KC_COS_CONFIG:-${CONFIG_DIR}/cos-online.env}"

LOCAL_HOME="${KC_LOCAL_HOME:-/tmp/kc-system-lakefs}"
LOCAL_ENV="${LOCAL_HOME}/system-lakefs.env"
LOCAL_PROJECT="${KC_SYSTEM_LAKEFS_PROJECT:-kc-system-lakefs}"
LOCAL_COMPOSE="${ROOT}/scripts/lakefs/compose.yaml"

ONLINE_HOME="${KC_ONLINE_HOME:-/tmp/kc-cos-online}"
ONLINE_ENV="${ONLINE_HOME}/system-lakefs.env"
ONLINE_PROJECT="${KC_COS_LAKEFS_PROJECT:-kc-cos-online}"
ONLINE_COMPOSE="${ROOT}/scripts/lakefs/compose.cos.yaml"
ONLINE_TTYD_NAME="${KC_COS_TTYD_CONTAINER:-kc-cos-online-ttyd}"
ONLINE_SERVE_PID="${ONLINE_HOME}/kc-serve.pid"

CATALOG="${KC_CATALOG:-kr://acme/catalog}"
PRINCIPAL="${KC_AS:-admin}"
KNOWLEDGE="${KC_KNOWLEDGE_REPO:-kr://acme/knowledge}"

mkdir -p "$CONFIG_DIR"

port_in_use() {
  ss -H -ltn "sport = :$1" 2>/dev/null | grep -q .
}

choose_port() {
  local current="$1"
  local candidates="$2"
  local label="$3"
  if [[ -n "$current" ]]; then
    printf '%s' "$current"
    return
  fi
  local candidate
  for candidate in $candidates; do
    if ! port_in_use "$candidate"; then
      printf '%s' "$candidate"
      return
    fi
  done
  echo "FAIL: no free local port for $label" >&2
  exit 1
}

wait_http() {
  local url="$1"
  local deadline=$((SECONDS + 180))
  while (( SECONDS < deadline )); do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "FAIL: $url did not become ready" >&2
  return 1
}

read_kv() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 1
  local line
  line="$(grep -E "^${key}=" "$file" | tail -n 1 || true)"
  [[ -n "$line" ]] || return 1
  printf '%s' "${line#*=}"
}

active_plane() {
  if [[ -f "$ACTIVE_PLANE_FILE" ]]; then
    tr -d '[:space:]' <"$ACTIVE_PLANE_FILE"
    return
  fi
  printf '%s' "local"
}

write_active() {
  local plane="$1"
  local envfile="$2"
  printf '%s\n' "$plane" >"$ACTIVE_PLANE_FILE"
  cat >"$ACTIVE_ENV_FILE" <<EOF
# generated by scripts/kc-snapshot-plane.sh — not for git
export KC_SNAPSHOT_PLANE=$plane
# shellcheck disable=SC1091
source "$envfile"
EOF
  chmod 600 "$ACTIVE_ENV_FILE"
}

ensure_local_meta() {
  [[ -f "$LOCAL_ENV" ]] || return 0
  grep -q '^export KC_SNAPSHOT_PLANE=' "$LOCAL_ENV" || printf 'export KC_SNAPSHOT_PLANE=local\n' >>"$LOCAL_ENV"
  grep -q '^export KC_TTYD_URL=' "$LOCAL_ENV" || printf 'export KC_TTYD_URL="http://127.0.0.1:7683/"\n' >>"$LOCAL_ENV"
}

print_urls() {
  local plane="$1"
  local envfile="$2"
  # shellcheck disable=SC1090
  source "$envfile"
  local listen="${KC_SERVER_URL:-}"
  local ttyd="${KC_TTYD_URL:-}"
  cat <<EOF
active plane: ${plane}

  ttyd (kc CLI)  ${ttyd}
  console        ${listen}/console
  lakeFS API     ${KC_LAKEFS_URL}
  typed API      ${listen}   (browser / is 404)

EOF
}

cmd_local() {
  if [[ -f "$LOCAL_ENV" ]] && curl -fsS --max-time 2 http://127.0.0.1:7390/readyz >/dev/null 2>&1; then
    ensure_local_meta
    write_active local "$LOCAL_ENV"
    echo "using existing local MinIO plane"
    print_urls local "$LOCAL_ENV"
    return
  fi
  echo "starting local MinIO plane"
  "$ROOT/scripts/system-lakefs.sh" up
  ensure_local_meta
  write_active local "$LOCAL_ENV"
  print_urls local "$LOCAL_ENV"
}

load_cos() {
  if [[ ! -f "$COS_CONFIG" ]]; then
    echo "FAIL: missing ${COS_CONFIG}" >&2
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$COS_CONFIG"
  set +a
  if [[ -z "${COS_SECRET_ID:-}" ]]; then
    COS_SECRET_ID="$(read_kv "${HOME}/.env" COS_SECRET_ID || true)"
  fi
  if [[ -z "${COS_SECRET_KEY:-}" ]]; then
    COS_SECRET_KEY="$(read_kv "${HOME}/.env" COS_SECRET_KEY || true)"
  fi
  COS_SECRET_ID="$(printf '%s' "${COS_SECRET_ID:-}" | tr -d '\r')"
  COS_SECRET_KEY="$(printf '%s' "${COS_SECRET_KEY:-}" | tr -d '\r')"
  if [[ -z "${COS_SECRET_ID}" || -z "${COS_SECRET_KEY}" ]]; then
    echo "FAIL: fill COS_SECRET_ID and COS_SECRET_KEY in ${COS_CONFIG} (or ~/.env). Do not paste them into chat." >&2
    exit 1
  fi
  if [[ -z "${COS_STORAGE_NAMESPACE:-}" || -z "${LAKEFS_BLOCKSTORE_S3_ENDPOINT:-}" ]]; then
    echo "FAIL: ${COS_CONFIG} is incomplete" >&2
    exit 1
  fi
}

online_compose() {
  KC_LAKEFS_PORT="$LAKEFS_PORT" \
  LAKEFS_BLOCKSTORE_S3_ENDPOINT="$LAKEFS_BLOCKSTORE_S3_ENDPOINT" \
  LAKEFS_BLOCKSTORE_S3_PRE_SIGNED_ENDPOINT="$LAKEFS_BLOCKSTORE_S3_PRE_SIGNED_ENDPOINT" \
  LAKEFS_BLOCKSTORE_S3_REGION="${LAKEFS_BLOCKSTORE_S3_REGION:-${COS_REGION}}" \
  LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE="${LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE:-false}" \
  COS_SECRET_ID="$COS_SECRET_ID" \
  COS_SECRET_KEY="$COS_SECRET_KEY" \
  KC_LAKEFS_ENCRYPT_KEY="$KC_LAKEFS_ENCRYPT_KEY" \
  docker compose -p "$ONLINE_PROJECT" -f "$ONLINE_COMPOSE" "$@"
}

lakefs_base() {
  printf 'http://127.0.0.1:%s' "$LAKEFS_PORT"
}

setup_online_lakefs() {
  local status
  status="$(curl -sS -o /tmp/kc-lakefs-setup.json -w '%{http_code}' \
    -X POST "$(lakefs_base)/api/v1/setup_lakefs" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"kc\",\"key\":{\"access_key_id\":\"${LAKEFS_ACCESS}\",\"secret_access_key\":\"${LAKEFS_SECRET}\"}}")"
  case "$status" in
    200|201|409) return 0 ;;
  esac
  echo "FAIL: lakeFS setup returned HTTP $status" >&2
  cat /tmp/kc-lakefs-setup.json >&2 || true
  return 1
}

ensure_online_repo() {
  local name="$1"
  local namespace="$2"
  local status
  status="$(curl -sS -o /tmp/kc-lakefs-repo.json -w '%{http_code}' \
    -u "${LAKEFS_ACCESS}:${LAKEFS_SECRET}" "$(lakefs_base)/api/v1/repositories/${name}")"
  if [[ "$status" == "200" ]]; then
    return 0
  fi
  status="$(curl -sS -o /tmp/kc-lakefs-repo.json -w '%{http_code}' \
    -u "${LAKEFS_ACCESS}:${LAKEFS_SECRET}" \
    -X POST "$(lakefs_base)/api/v1/repositories" \
    -H 'Content-Type: application/json' \
    -d "{\"name\":\"${name}\",\"storage_namespace\":\"${namespace}\",\"default_branch\":\"main\"}")"
  case "$status" in
    201) return 0 ;;
  esac
  echo "FAIL: create lakeFS repository ${name} returned HTTP $status" >&2
  cat /tmp/kc-lakefs-repo.json >&2 || true
  return 1
}

write_online_env() {
  mkdir -p "$ONLINE_HOME/bin"
  cat >"$ONLINE_ENV" <<EOF
export KC_SNAPSHOT_PLANE=online
export KC_DEPLOYMENT_CONFIG="${ONLINE_HOME}/deployment.json"
export KC_LAKEFS_URL="$(lakefs_base)"
export KC_LAKEFS_CREDENTIAL="${LAKEFS_ACCESS}:${LAKEFS_SECRET}"
export KC_LAKEFS_PORT="${LAKEFS_PORT}"
export KC_LAKEFS_ENCRYPT_KEY="${KC_LAKEFS_ENCRYPT_KEY}"
export KC_AS="${PRINCIPAL}"
export KC_CATALOG="${CATALOG}"
export KC_SERVER_URL="http://127.0.0.1:${KC_LISTEN_PORT}"
export KC_TTYD_URL="http://127.0.0.1:${TTYD_PORT}/"
export PATH="${ONLINE_HOME}/bin:\$PATH"
EOF
  chmod 600 "$ONLINE_ENV"
}

stop_online_serve() {
  if [[ -f "$ONLINE_SERVE_PID" ]]; then
    local pid
    pid="$(cat "$ONLINE_SERVE_PID" 2>/dev/null || true)"
    if [[ -n "$pid" ]] && kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
      wait "$pid" 2>/dev/null || true
    fi
    rm -f "$ONLINE_SERVE_PID"
  fi
}

start_online_serve() {
  stop_online_serve
  write_online_env
  mkdir -p "$ONLINE_HOME/bin"
  "$GO" build -o "$ONLINE_HOME/bin/kc" ./cmd/kc
  # shellcheck disable=SC1090
  source "$ONLINE_ENV"
  nohup "$ONLINE_HOME/bin/kc" serve --config "${ONLINE_HOME}/deployment.json" --listen "127.0.0.1:${KC_LISTEN_PORT}" \
    >"${ONLINE_HOME}/kc-serve.log" 2>&1 &
  echo $! >"$ONLINE_SERVE_PID"
  wait_http "http://127.0.0.1:${KC_LISTEN_PORT}/readyz"
}

start_online_ttyd() {
  docker rm -f "$ONLINE_TTYD_NAME" >/dev/null 2>&1 || true
  cat >"${ONLINE_HOME}/.bash_profile" <<EOF
source "${ONLINE_ENV}"
PS1='kc-cos:\\w\\\$ '
cd "${ONLINE_HOME}"
echo "plane=online  KC_SERVER_URL=\$KC_SERVER_URL  catalog=\$KC_CATALOG"
echo "example: kc schema list --repo kr://kc/system --as \$KC_AS"
EOF
  docker run -d --name "$ONLINE_TTYD_NAME" \
    --network host \
    --label kc.cos-online=1 \
    -v "${ONLINE_HOME}:${ONLINE_HOME}" \
    -e HOME="${ONLINE_HOME}" \
    -w "${ONLINE_HOME}" \
    tsl0922/ttyd:1.7.7 \
    ttyd --port "$TTYD_PORT" --interface 127.0.0.1 -W bash --login >/dev/null
}

cmd_online() {
  load_cos
  if ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
    echo "FAIL: Docker daemon is unavailable" >&2
    exit 1
  fi
  mkdir -p "$ONLINE_HOME"
  if [[ ! -f "${ONLINE_HOME}/lakefs-encrypt.key" ]]; then
    openssl rand -hex 16 >"${ONLINE_HOME}/lakefs-encrypt.key"
    chmod 600 "${ONLINE_HOME}/lakefs-encrypt.key"
  fi
  if [[ ! -f "${ONLINE_HOME}/lakefs-admin.env" ]]; then
    cat >"${ONLINE_HOME}/lakefs-admin.env" <<EOF
LAKEFS_ACCESS=${KC_LAKEFS_ACCESS_KEY:-AKIAKOSONLINEEXAMPLE}
LAKEFS_SECRET=${KC_LAKEFS_SECRET_KEY:-$(openssl rand -hex 16)}
EOF
    chmod 600 "${ONLINE_HOME}/lakefs-admin.env"
  fi
  # shellcheck disable=SC1091
  source "${ONLINE_HOME}/lakefs-admin.env"
  KC_LAKEFS_ENCRYPT_KEY="$(tr -d '\n' <"${ONLINE_HOME}/lakefs-encrypt.key")"
  if [[ -f "$ONLINE_ENV" ]]; then
    # shellcheck disable=SC1090
    source "$ONLINE_ENV"
    LAKEFS_PORT="${KC_LAKEFS_PORT:-}"
    KC_LISTEN_PORT="${KC_SERVER_URL##*:}"
    TTYD_PORT="${KC_TTYD_URL#*://}"
    TTYD_PORT="${TTYD_PORT#*:}"
    TTYD_PORT="${TTYD_PORT%%/*}"
  else
    LAKEFS_PORT=""
    KC_LISTEN_PORT=""
    TTYD_PORT=""
  fi
  LAKEFS_PORT="$(choose_port "${LAKEFS_PORT:-}" "18010 18011 18012 18013" lakefs-cos)"
  KC_LISTEN_PORT="$(choose_port "${KC_LISTEN_PORT:-}" "7394 7395 7396 7397" kc-serve-cos)"
  TTYD_PORT="$(choose_port "${TTYD_PORT:-}" "7688 7689 7690 7691" ttyd-cos)"
  echo "starting online COS plane (lakeFS ${LAKEFS_PORT})"
  online_compose up -d
  if ! wait_http "$(lakefs_base)/_health"; then
    online_compose logs --tail 80 lakefs >&2 || true
    exit 1
  fi
  setup_online_lakefs
  local ns
  ns="$(printf '%s' "$COS_STORAGE_NAMESPACE" | sed 's:/*$::')"
  ensure_online_repo kc-catalog "${ns}/kc-catalog"
  ensure_online_repo kc-system "${ns}/kc-system"
  ensure_online_repo kc-knowledge "${ns}/kc-knowledge"
  write_online_env
  export KC_LAKEFS_CREDENTIAL="${LAKEFS_ACCESS}:${LAKEFS_SECRET}"
  if [[ ! -f "${ONLINE_HOME}/deployment.json" ]]; then
    "$GO" run ./scripts/fixture-deployment \
      --root "$ONLINE_HOME" \
      --catalog "$CATALOG" \
      --catalog-driver lakefs \
      --catalog-dsn "$(lakefs_base)/kc-catalog" \
      --principal "$PRINCIPAL" \
      --lakefs-repo "kr://kc/system=$(lakefs_base)/kc-system" \
      --lakefs-repo "${KNOWLEDGE}=$(lakefs_base)/kc-knowledge" >/dev/null
  fi
  "$GO" run ./cmd/kc -- deployment init --config "${ONLINE_HOME}/deployment.json" >/dev/null
  "$GO" run ./cmd/kc -- deployment system publish --config "${ONLINE_HOME}/deployment.json"
  start_online_serve
  start_online_ttyd
  write_active online "$ONLINE_ENV"
  echo "online COS plane is ready"
  print_urls online "$ONLINE_ENV"
}

plane_health() {
  local name="$1"
  local envfile="$2"
  if [[ ! -f "$envfile" ]]; then
    printf '%s  not provisioned\n' "$name"
    return
  fi
  # shellcheck disable=SC1090
  source "$envfile"
  local lake="down" serve="down"
  if [[ -n "${KC_LAKEFS_URL:-}" ]] && curl -fsS --max-time 2 "${KC_LAKEFS_URL}/_health" >/dev/null 2>&1; then
    lake="up"
  fi
  if [[ -n "${KC_SERVER_URL:-}" ]] && curl -fsS --max-time 2 "${KC_SERVER_URL}/readyz" >/dev/null 2>&1; then
    serve="up"
  fi
  printf '%s  lakefs=%s  serve=%s  %s\n' "$name" "$lake" "$serve" "${KC_LAKEFS_URL:-}"
}

cmd_status() {
  echo "active: $(active_plane)"
  plane_health local "$LOCAL_ENV"
  plane_health online "$ONLINE_ENV"
  if [[ -f "$COS_CONFIG" ]]; then
    local sid
    sid="$(read_kv "$COS_CONFIG" COS_SECRET_ID || true)"
    if [[ -z "$sid" ]]; then
      echo "online keys: missing in ${COS_CONFIG}"
    else
      echo "online keys: present in ${COS_CONFIG}"
    fi
  else
    echo "online keys: no ${COS_CONFIG}"
  fi
}

cmd_down() {
  local plane="${TARGET:-$(active_plane)}"
  case "$plane" in
    local)
      "$ROOT/scripts/system-lakefs.sh" down
      ;;
    online)
      if [[ -f "$ONLINE_ENV" ]]; then
        # shellcheck disable=SC1090
        source "$ONLINE_ENV"
        LAKEFS_PORT="${KC_LAKEFS_PORT:-}"
      fi
      stop_online_serve
      docker rm -f "$ONLINE_TTYD_NAME" >/dev/null 2>&1 || true
      if docker compose -p "$ONLINE_PROJECT" -f "$ONLINE_COMPOSE" ps -q >/dev/null 2>&1; then
        docker compose -p "$ONLINE_PROJECT" -f "$ONLINE_COMPOSE" down >/dev/null
      fi
      echo "stopped $ONLINE_PROJECT"
      ;;
    *)
      echo "usage: $0 down [local|online]" >&2
      exit 2
      ;;
  esac
}

case "$CMD" in
  local) cmd_local ;;
  online) cmd_online ;;
  status) cmd_status ;;
  down) cmd_down ;;
  *)
    echo "usage: $0 local|online|status|down [local|online]" >&2
    exit 2
    ;;
esac
