apiVersion: 1

datasources:
  - name: Prometheus (KC)
    uid: kc-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: "Trace: $${__value.raw}"

  - name: Loki (KC)
    uid: kc-loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id[=:]"?([a-f0-9]{32})'
          datasourceUid: tempo
          url: "$${__value.raw}"
          urlDisplayLabel: "Trace: $${__value.raw}"
